### PR TITLE
Visualize Protein with Graphs

### PR DESCRIPTION
**Pull request by rajinderpalsingh2001**
- Pass a dictionary of protein_count, will plot a graph based upon graphtype('line' or 'bar' or 'pie').

- customize color by setting graphcolor='colorcode or colorname', By default = 'maroon' (optional)
- Change size of graph by setting dpival= integer_value, By default=100 (optional)
    
Input: Dictionary of Protein Count(required), plottype(required), graphcolor(optional), dpival(optional)
Output: Matplotlib Graph object

Updated requirements.txt

### CODE REVIEW

**Comment by vaibhavarora102** [comment]
can you pls tell us how will we get the protein count? can you pls make another function within it that could make a dictionary out of DNA sequence and then call that function in the present function itself?

- dedicate a single line for each input argument in a docstring and explain one argument in one line

**Comment by rajinderpalsingh2001** [comment]
bycalling rnaToProtein() function and setting proteincount= True, we can get the protein count. Which we can use to visualise the protein sequence

Btw, I will make a separate function for getting protein count as well

**Comment by vaibhavarora102** [comment]
yups! 
it would beasy for other to visualize

**Comment by rajinderpalsingh2001** [comment]
Can you please tell, How can I modify this function, either we let the user to pass a Sequence of (RNA or DNA) or direct protein count?

**Comment by vaibhavarora102** [comment]
pass RNA sequence or DNA sequence

**Pull request closed without merging**
