### PR TITLE
added contributers section --issue44

### PR DESCRIPTION
**Pull request by Ayan-thecodeking**
hey @vaibhavarora102  please review my PR .... and let me know if there is anything more left for updating 
thanks for assigning :)

### CODE REVIEW

**Comment by vaibhavarora102** [comment]
there is an extra box enclosing contributors, kindly remove that else looks nice

**Comment by Ayan-thecodeking** [comment]
> there is an extra box enclosing contributors, kindly remove that else looks nice

that underline one u are telling ? Sry I didn't get @vaibhavarora102

**Comment by vaibhavarora102** [comment]
no, actually there is the proper border of the box in which contributors are visible, just remove that thing

**Comment by Ayan-thecodeking** [comment]
> no, actually there is the proper border of the box in which contributors are visible, just remove that thing

ok done @vaibhavarora102  ..please check it now

**Pull request closed without merging**
